# Python Programming Basic Assignment 13


### 1. Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 C D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24

In [9]:
import math
c=50
h=30
d=[int(x) for x in input().split(',')]
q=[int(math.sqrt((10/3)*x)) for x in d]
print(q)

 89,21,45


[17, 8, 12]


### 2. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

In [3]:
import numpy as np
x,y=[int(x) for x in input("Enter the values of x,y:").split(',')]
a=np.zeros((x,y))
for i in range(x):
    for j in range(y):
        a[i][j]=int(i*j)
print(a)

Enter the values of x,y: 9,9


[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 0.  2.  4.  6.  8. 10. 12. 14. 16.]
 [ 0.  3.  6.  9. 12. 15. 18. 21. 24.]
 [ 0.  4.  8. 12. 16. 20. 24. 28. 32.]
 [ 0.  5. 10. 15. 20. 25. 30. 35. 40.]
 [ 0.  6. 12. 18. 24. 30. 36. 42. 48.]
 [ 0.  7. 14. 21. 28. 35. 42. 49. 56.]
 [ 0.  8. 16. 24. 32. 40. 48. 56. 64.]]


### 3. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

In [20]:
a=[]
a=[x for x in input("Enter the comma separated sequence of words: ").split(',')]
a.sort()
print(a)

Enter the comma separated sequence of words:  divya,aditya


['aditya', 'divya']


### 4. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

In [24]:
a=[]
a=[x for x in input("Enter the comma separated sequence of words: ").split(' ')]
a=list(set(a))
a.sort()
print(a)

Enter the comma separated sequence of words:  all is the man is te


['all', 'is', 'man', 'te', 'the']


### 5. Write a program that accepts a sentence and calculate the number of letters and digits.

In [30]:
a=input("Enter any sentence: ")
letters=0
digits=0
for i in a:
    if(i.isalpha()):
        letters+=1
    elif(i.isnumeric()):
        digits+=1
print("There are {} letters and {} digits.".format(letters,digits))

Enter any sentence:  cow has 4 legs and 2 ears and 2 eyes


There are 24 letters and 3 digits.


### 6. A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

In [16]:
import re
a=input("Enter any password: ")
regex=re.compile('[@_!#$%^&*()<>?/\|}{~:]')
if(regex.search(a)!=None and re.search("[a-z]",a)!=None and re.search("[A-Z]",a)!=None and re.search("[1-9]",a)!=None):
    print("Valid Password")
else:
    print("Invalid Password")

Enter any password:  ADITYA@12


Invalid Password
